# Generated by Django 4.1.7 on 2023-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_App', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='tuition/images'),
        ),
    ]
