# Generated by Django 4.1.7 on 2023-09-26 04:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_App', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('English', 'English'), ('Math', 'Math'), ('physics', 'physics'), ('Biology', 'Biology')], default='bangla', max_length=100),
        ),
    ]
