# Generated by Django 4.1.7 on 2023-09-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_App', '0015_class_in_subject_post_class_in_post_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_in',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Class_in',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
