# Generated by Django 4.1.7 on 2023-09-27 03:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_App', '0017_class_in_subject_post_class_in_post_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='salay',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tuition/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=101), max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=101),
        ),
    ]
